spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://127.0.0.1:5432/article_manager}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
  sql:
    init:
      mode: never

app:
  jwt:
    secret: ${JWT_SECRET:U73dsIlmL5e6wfYslsop3TsVLPGxYeE9sDOjxxGXTOo=}
    expiration: ${JWT_EXPIRATION:86400000}

server:
  port: 8080

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
